### ISSUE TITLE
Evaluate better step-down for 12V Digital I/O.

### ISSUE THREAD

**Issue by willson556** [CalPolyFSAE/EAGLE-Designs#3]
Since the car 12V ranges between 10V-15V, Zener diodes don't provide a safe way of settling down voltages to 3.3V. There is some possibility of current limiting resistors being sufficient to solve this problem (see http://www.xilinx.com/support/answers/10835.html) but you may also be able to find an IC that is a more elegant solution for the many inputs we have.

**Comment by mikecool1000** [comment]
I could use a logic level converter fairly easily. I hadn't really thought about that though, good point.

**Comment by willson556** [comment]
Yeah, it seemed fine when I originally did it but with the huge range of 12V we use it wasn't a very smart call on my part.

**Comment by mikecool1000** [comment]
I'm going to use some  [SOT23-5 linear regulators](http://www.digikey.com/product-detail/en/MIC5225-3.3YM5-TR/576-2980-1-ND/1815455) with an input voltage range from 3-16V. This could also be a good system for any low speed digital inputs, as it could allow us to have somewhat arbitrary input voltages. Here is a link to the regulators I am looking at :

**Comment by mikecool1000** [comment]
I lied, [here](http://www.digikey.com/product-detail/en/MCP1703T-3302E%2FCB/MCP1703T-3302E%2FCBCT-ND/1776945) is the one i'm using now.

**Comment by willson556** [comment]
Looks good!
