### ISSUE TITLE
An input should be provided for the lap timer beacon.

### ISSUE THREAD

**Issue by willson556** [CalPolyFSAE/EAGLE-Designs#7]
Just needs to be simple DIO with a pull-up resistor to 5V. I'll get back to you on the resistance value. 0603 package should be fine.

**Comment by willson556** [comment]
Oh, and it needs to be converted down to 3.3V in a high-impedance manner (i.e. not a regulator). A MOSFET inverter would be fine.

**Comment by mikecool1000** [comment]
Done
